services:
  discoverer:
    build:
      context: .
      dockerfile: Discoverer.dockerfile
    networks:
      - gossip_demonet
    env_file:
      - .env_compose

  peer:
    depends_on:
      - discoverer
    build:
      context: .
      dockerfile: Peer.dockerfile
    networks:
      - gossip_demonet
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnssr
    env_file:
      - .env_compose

networks:
  gossip_demonet : {}